<?php

$locations = [
    // Academic & Research
    'Amos Eaton Hall',
    'Carnegie Building',
    'Center for Biotechnology and Interdisciplinary Studies (CBIS)',
    'Cogswell Laboratory',
    'Darrin Communications Center',
    'Empire State Hall',
    'Experimental Media & Performing Arts Center (EMPAC)',
    'Folsom Library',
    'Greene Building',
    'Jonsson Engineering Center (JEC)',
    'Jonsson-Rowland Science Center',
    'Lally Hall',
    'LINAC Facility (Gaerttner Laboratory)',
    'Low Center for Industrial Innovation (CII)',
    'Materials Research Center (MRC)',
    'Pittsburgh Building',
    'Ricketts Building',
    'Russell Sage Laboratory',
    'Walker Laboratory',
    'West Hall',
    'Winslow Building',

    // Student Life
    '87 Gymnasium',
    'Academy Hall',
    'Alumni Sports & Recreation Center',
    'Chapel + Cultural Center',
    'Commons Dining Hall',
    'East Campus Athletic Village Arena (ECAV)',
    'East Campus Athletic Village Stadium',
    'Houston Field House',
    'Mueller Center',
    'Playhouse',
    'Radio Club W2SZ',
    'Rensselaer Union',
    'Robison Swimming Pool',
    'Russell Sage Dining Hall',

    // Student Housing
    'Barton Hall',
    'Blitman Commons',
    'Bray Hall',
    'Bryckwyck',
    'Burdett Avenue Residence Hall',
    'Colonie Apartments',
    'Hall Hall',
    'Nason Hall',
    'North Hall',
    'Nugent Hall',
    'Polytechnic Residence Commons',
    'Quadrangle Complex',
    'Rensselaer Apartment Housing Project A',
    'Rensselaer Apartment Housing Project B',
    'Rousseau Apartments',
    'Sharp Hall',
    'Stacwyck Apartments',
    'Warren Hall',
    'Williams Apartments',

    // Operations & Administration
    '2021 15th Street',
    '2144 Burdett Avenue',
    '41 Ninth Street',
    'Admissions',
    'Alumni House (Heffner)',
    'Blaw-Knox 1 & 2',
    'Boiler House, 11th Street',
    'Boiler House, Sage Avenue',
    'Graduate Education',
    'Greenhouses and Grounds Barn',
    'H Building',
    'J Building',
    'Patroon Manor',
    'Public Safety',
    'Service Building',
    'Troy Building',
    'Voorhees Computing Center (VCC)'
];

echo json_encode($locations);